from app.domain.errors.exceptions import (
    AppError,
    AudioExtractionError,
    BotForbiddenError,
    DownloadError,
    DownloadUnavailableError,
    InvalidCachedMediaError,
    MediaTooLargeError,
    MusicDownloadError,
    MusicNotFoundError,
    MusicQueryValidationError,
    NormalizationError,
    ProcessingConflictError,
    RateLimitExceededError,
    TelegramDeliveryError,
    UnsupportedUrlError,
)

__all__ = [
    "AppError",
    "AudioExtractionError",
    "BotForbiddenError",
    "DownloadError",
    "DownloadUnavailableError",
    "InvalidCachedMediaError",
    "MediaTooLargeError",
    "MusicDownloadError",
    "MusicNotFoundError",
    "MusicQueryValidationError",
    "NormalizationError",
    "ProcessingConflictError",
    "RateLimitExceededError",
    "TelegramDeliveryError",
    "UnsupportedUrlError",
]
