from app.domain.errors.exceptions import (
    AppError,
    AudioExtractionError,
    BotForbiddenError,
    DownloadError,
    DownloadUnavailableError,
    InvalidCachedMediaError,
    InvalidTrackQueryError,
    MediaTooLargeError,
    NormalizationError,
    ProcessingConflictError,
    RateLimitExceededError,
    TelegramDeliveryError,
    TrackDownloadError,
    TrackNotFoundError,
    UnsupportedUrlError,
)

__all__ = [
    "AppError",
    "AudioExtractionError",
    "BotForbiddenError",
    "DownloadError",
    "DownloadUnavailableError",
    "InvalidCachedMediaError",
    "InvalidTrackQueryError",
    "MediaTooLargeError",
    "NormalizationError",
    "ProcessingConflictError",
    "RateLimitExceededError",
    "TelegramDeliveryError",
    "TrackDownloadError",
    "TrackNotFoundError",
    "UnsupportedUrlError",
]
